# Generated by Django 5.2.1 on 2025-05-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchplan',
            name='hgap',
            field=models.ForeignKey(limit_choices_to={'user_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'user_type': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_received', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'WAREHOUSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment'),
        ),
    ]
